nixos/redis: fix evaluation
Commit e8a8f2ce0119e6f06cba020e52455192f818a36d ("nixos/redis: clean up
option types") broke nixos evaluation:

  error: attempt to call something which is not a function but a set, at .../nixpkgs/nixos/modules/services/databases/redis.nix:111:28

Fix it.

Reported by Oliver Charles (thanks!).